Move from Maven to Gradle
4b8t-reincarnated/AnarchyUtils pull request #16
Opened 2024-10-20 00:56 UTC by wolfieboy09

2024-10-20 01:08 UTC, wolfieboy09 commented
Do not merge or anything until I get my latest commits pushed. Will update once it has been pushed and git lets me push

![image](https://github.com/user-attachments/assets/dc1a7f03-6cf7-47e5-a7f2-932135f7693e)

2024-10-22 03:11 UTC, alex-ritter requested changes
We need to add gradle dependencies in the .gitignore.

We shouldn't have the .gradle folder checked into source control.

2024-10-22 17:24 UTC, alex-ritter approved these changes
LGTM

2024-10-22 17:25 UTC, wolfieboy09 commented on build.gradle~
> +import org.apache.tools.ant.filters.ReplaceTokens
I don't know why its the same file but with a `~` attached, so we can remove it

2024-10-22 17:26 UTC, merged